### ISSUE TITLE
Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by xiu-shen** [mos9527/evbunpack#5]
Enigma Virtual Box Unpacker v0.1.9.4.1
Traceback (most recent call last):
  File "evbunpack\__main__.py", line 405, in <module>
  File "evbunpack\__main__.py", line 339, in __main__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kmeng\\Desktop\\vic'
[14044] Failed to execute script '__main__' due to unhandled exception!

**Comment by mos9527** [comment]
试试给文件名加上引号？
或者也可以试试把文件拖到命令行窗口
看起来不像是unpacker的问题😓

**Comment by xiu-shen** [comment]
C:\Users\kmeng\Desktop\1>evbunpack "C:\Users\kmeng\Desktop\vic 2+3gen\vic\2d\Vic2D.exe"
usage: evbunpack [-h] [--ignore-fs] [--ignore-pe IGNORE_PE] [--legacy]
                 [--list]
                 file output
evbunpack: error: the following arguments are required: output

**Comment by xiu-shen** [comment]
已经文件拖到命令行窗口，但是是直接闪退的

**Comment by xiu-shen** [comment]
方便的话可以留您一个联系方式吗

**Comment by mos9527** [comment]
看我主页吧
https://mos9527.github.io/
留了qq，可以加我问下
那就先关issue了😉

**Comment by qwertyu131** [comment]
evbunpack.exe "C:\Users\****\Desktop\ConsoleApplication3_protect.exe" ./extract --legacy
Enigma Virtual Box Unpacker v0.1.9.4.1
[!] Legacy mode enabled
[-] Loading PE...
Traceback (most recent call last):
  File "evbunpack\__main__.py", line 405, in <module>
  File "evbunpack\__main__.py", line 344, in __main__
  File "evbunpack\__main__.py", line 214, in restore_pe
  File "evbunpack\__main__.py", line 211, in <lambda>
StopIteration
[25776] Failed to execute script '__main__' due to unhandled exception!
