### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ycaosbiann** [mos9527/evbunpack#9]
C:\Users\PC\Downloads\Compressed\ABC>evbunpack ABCD.dll output
INFO: Enigma Virtual Box Unpacker v0.2.3
WARNING: Legacy mode for PE restoration enabled
INFO: Extracting virtual filesystem
ERROR: Unhandled exception occured while extracting virtual filesystem: EVB filesystem magic not found. Cannot proceed.
Traceback (most recent call last):
  File "evbunpack\__main__.py", line 558, in <module>
  File "evbunpack\__main__.py", line 544, in __main__
  File "evbunpack\__main__.py", line 483, in main
  File "evbunpack\__main__.py", line 477, in main
  File "evbunpack\__main__.py", line 391, in unpack_files
AssertionError: EVB filesystem magic not found. Cannot proceed.
[PYI-19300:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by mos9527** [comment]
See https://github.com/mos9527/evbunpack/issues/8
[BTW Errors like this would receive more thorough explainations starting from 0.2.4.](https://github.com/mos9527/evbunpack/commit/2cdb918692e0de324933cef58fdbeeffc6d47c04)
